### PR TITLE
Add Vue.js

### PR DESCRIPTION
**Pull request by pedroborges**
I fixed a few errors and tried each Vue.js example separately to make sure it is correct. Take a look at my Vue.js benchmark implementation.

### CODE REVIEW

**Comment by antonmedv** [comment]
Cool!

**Comment by antonmedv** [comment]
Does repeated rendering looks broken?

**Comment by pedroborges** [comment]
I don't think so, if you copy that test and run it separately it works just fine. Crazy results thou!

My guess it that the way Vue.js works makes it shine in this particular case:

> `v-if` is also lazy: if the condition is false on initial render, it will not do anything - partial compilation won’t start until the condition becomes true for the first time (and the compilation is subsequently cached).

And:

> … contrary to the common misconception that Virtual-DOM makes React faster than anything else, Vue.js actually out-performs React when it comes to hot updates, and requires almost no hand-tuned optimization.

**Comment by antonmedv** [comment]
No, it's looks like something goes wrong :) I need more time for testing.

**Comment by antonmedv** [comment]
I was right.

Read this: https://vuejs.org/guide/reactivity.html#Async-Update-Queue

> By default, Vue.js performs DOM updates **asynchronously**

So there was no actual DOM updates and bench was measuring nothing. To trigger real update we need to call Vue.nextTick(callback). After doing this a got true results:

> Monkberry 2 513 op/sec ±1.76% (55 runs sampled)
> React 361 op/sec ±4.39% (49 runs sampled)
> Vue 53.50 op/sec ±14.22% (39 runs sampled)
> Template string 393 op/sec ±6.33% (28 runs sampled)

It's actually _slower_ than react, and monkberry.

There is no magic.

**Comment by antonmedv** [comment]
Fixed and merged vue.js. The only good result vue.js in single-point-rendering: vue beats react, but still it's **30 times** slower than Monkberry.

**Pull request merged**
