### PR TITLE
Adds Inferno 0.7.15 to benchmarks

### PR DESCRIPTION
**Pull request by trueadm**
Another "vdom" library for comparison in your benchmarks. :)

### CODE REVIEW

**Comment by antonmedv** [comment]
Hi,

Cool, but can you rebase it?

**Comment by trueadm** [comment]
@elfet Fixed. :)

**Comment by trueadm** [comment]
@elfet is there anything stopping this being merged now?

**Comment by antonmedv** [comment]
Merged. Also added single point rendering.

**Pull request merged**
